name: scanex
description: "Scanex - Optical Form Reader & Auto Grader"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  camera: any
  image: any
  google_mlkit_text_recognition: any
  pdf: any
  printing: any
  excel: any
  sqflite: any
  path: any
  provider: any
  share_plus: any
  path_provider: any
  permission_handler: any
  google_fonts: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: any

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "app_icon.png"
  adaptive_icon_background: "#3BA5A8"
  adaptive_icon_foreground: "app_icon.png"

flutter:
  uses-material-design: true
